inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Lint/UnusedMethodArgument:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Security/YAMLLoad:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

Performance/CollectionLiteralInLoop:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/MethodName:
  Enabled: true

Naming/VariableNumber:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/WordArray:
  MinSize: 3

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma