services:
  app:
    build:
      context: .
      target: build
    user: "${UID}:${GID}"
    volumes:
      - .:/home/appuser/app
      - vendor_bundle:/home/appuser/vendor/bundle

volumes:
  vendor_bundle: