name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version, .tool-versions or mise.toml
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run Bundler Audit
        run: |
          bundle exec bundler-audit update
          bundle exec bundler-audit check --update

      - name: Run RuboCop
        run: bundle exec rubocop --no-color --no-parallel

      - name: Run RSpec with Formatter and Coverage
        run: |
          # This command assumes you have configured SimpleCov to generate an HTML coverage report
          bundle exec rspec

      - name: Run RubyCritic
        run: bundle exec rubycritic --no-browser

      # Upload artifacts so that you can later review the HTML reports and test result files.
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-report
          path: coverage/           # Folder generated by SimpleCov (HTML files)

      - name: Upload RubyCritic Report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: rubycritic-report
          path: tmp/rubycritic/     # Default output folder for RubyCritic
